version: '0.1.0.0'
name: musfix
synopsis: Greatest Fixpoint Horn Solver from Synquid
category: Language
author:
- Nadia Polikarpova
- Conner Irwin
- Kevin Hine
maintainer: cjirwin@ucsd.edu
license: OtherLicense
dependencies:
- ansi-wl-pprint >= 0.6 && < 0.7
- ansi-terminal >= 0.6
- atto-lisp == 0.2.*
- attoparsec >= 0.10 && < 0.14
- base >= 4.6 && < 4.9
- bimap >= 0.2
- bytestring >= 0.10
- containers >= 0.5 && < 0.6
- directory
- filepath
- lens >= 3.7
- mtl >= 2.2 && < 2.3
# - optparse-applicative >= 0.14
- parsec == 3.1.*
- scientific >= 0.3
- tasty >= 1.0.1
- tasty-golden >= 2.3.2
- text >= 1.2
- transformers >= 0.3 && < 0.5
- z3 > 4.0
library:
  source-dirs: src
executable:
  source-dirs:
  - src
  - app
  main: Main.hs
# ghc-options:
# - -Wall
# - -fwarn-tabs
# - -fwarn-incomplete-uni-patterns
# - -fwarn-incomplete-record-updates
# - -O2
tests:
  specs:
    source-dirs:
    - app
    - src
    - test
    main: MusfixTests.hs
    ghc-options: -main-is Harness
