name: musfix
version: '0.1.0.0'
synopsis: Greatest Fixpoint Horn Solver from Synquid
category: Language
author:
- Nadia Polikarpova
- Conner Irwin
- Kevin Hine
maintainer: cjirwin@ucsd.edu
license: UnspecifiedLicense
dependencies:
- ansi-wl-pprint >=0.6 && <0.7
- ansi-terminal >=0.6
- atto-lisp ==0.2.*
- base >=4.6 && <4.9
- bimap >= 0.2
- containers >=0.5 && <0.6
- lens >=3.7
- mtl >=2.2 && <2.3
- parsec == 3.1.*
- transformers >=0.3 && <0.5
- z3 >4.0
library:
  source-dirs: src
